name: Publish to GitHub Container Registry

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          docker build -t ghcr.io/${{ github.repository_owner }}/application:$TAG_NAME -f ./Dockerfile .

      - name: Push the container image
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          docker push ghcr.io/${{ github.repository_owner }}/application:$TAG_NAME
